export {default as Navbar} from './navbar'
export {default as Header} from './header'
export {default as Projects} from './projects'
export {default as Techstack} from './techstack'
export {default as Footer} from './footer'
export {default as Modal} from './modal'